### ISSUE TITLE
Drop-in demo returns 'Error! Reason: Cancelled' using valid test cards

### ISSUE THREAD

**Issue by MPV65** [adyen-examples/adyen-dotnet-online-payments#2] opened 2021-03-31 12:45 UTC
I have been trying out the drop-in demo using various test card numbers from https://docs.adyen.com/development-resources/test-cards/test-card-numbers. However, so far these have all returned the 'Error! Reason: Cancelled' message, even though I have successfully tested the same numbers using curl and prefixing the numbers with 'test_'. The response from the server is:

info: adyen_dotnet_online_payments.Controllers.ApiController[0]
      Response for Payment API::
class PaymentResponse {
  Action:
  AdditionalData:
  Amount:
  Authentication:
  Details:
  DonationToken:
  FraudResult:
  MerchantReference: 39b82c21-fe7d-4d6e-a6ac-108cdb498d75
  Order:
  OutputDetails:
  PaymentData:
  PspReference: 883617192418467H
  Redirect:
  RefusalReason: FRAUD-CANCELLED
  RefusalReasonCode: 22
  ResultCode: Cancelled
}

Using curl with, for instance:

    "paymentMethod": {
    "type": "scheme",
    "encryptedCardNumber": "test_5555444433331111",
    "encryptedExpiryMonth": "test_03",
    "encryptedExpiryYear": "test_2030",
    "encryptedSecurityCode": "test_737"
  }

(using the same number) I get the resultCode  "Authorised".

**Comment by deepu105** [comment] 2021-03-31 13:35
Thanks for reporting this. I'll take a look

**Comment by deepu105** [comment] 2021-04-02 14:34
Hi I tried this and couldn't reproduce. The test cards are working fine. Seems like in your case the request is going to fraud detection flow for some reason. Could be an intermittent test system issue. can you please try gain? if it still fails give me the psp ref from response i'll dig in further

**Comment by MPV65** [comment] 2021-04-06 07:47
Hi Deepu
I haven't had a chance to try this again. However, in the meantime, I did get this response from Adyen to a technical request I raised with them, which may throw some light on the issue. Note that I could get the same card numbers to work correctly using curl (in Postman) and prefixing the numbers with 'test_' without encryption.
Best regards,
Martin




| ------##- Please type your reply above this line -##------ |
|  |
| 
Hi ,

This is an email to remind you that your request #1973819 has been pending for 3 days and awaits your feedback. This request will be closed in 2 days from now if no update on the ticket is provided.



| 
|  | 
Stella Liang (Adyen)

Mar 31, 2021, 20:12 GMT+2
Hi Martin,

Thanks for reaching out! The transaction was cancelled by our fraud engine, which happens when the total fraud score for the shopper exceeds 99 points. You can review the risk results for a shopper through Customer Area > search payments > click on PSP reference > fraud scoring > click on the fraud score.

You can disable risk through Customer Area:  Log in to Customer Area > Risk > Risk Settings. It will be the first item you see on the page.

You can also add the shopper to the trust list to decrease the fraud score. Please see documentation here: https://www.adyen.help/hc/en-us/articles/115001179984-How-do-I-block-or-trust-a-shopper-.

Please let us know if you have any questions.

Best,

Stella Liang
Technical Support Engineer
Adyen


 |

 |




| 
|  | 
Martin Vaughan

Mar 31, 2021, 14:24 GMT+2

I have cloned the https://github.com/adyen-examples/adyen-dotnet-online-payments.git repository and run it locally on my machine. I have been trying some of the test card numbers given on Test card numbers | Adyen Docs on the drop-in demo. However, using these returns the error that the card is cancelled.


| 
| 
|  | 
Test card numbers | Adyen Docs

Test your integration with our test card numbers and payment method details.
 |

 |

 |




The numbers I have tried are:

(Mastercard)


2222 40▇▇ ▇▇▇▇ 0005   Commercial Debit   CA   03/2030   737

5555 34▇▇ ▇▇▇▇ 1115    Consumer   NL   03/2030   737

5555 44▇▇ ▇▇▇▇ 1111   Consumer   GB   03/2030   737

Example server response:

info: adyen_dotnet_online_payments.Controllers.ApiController[0]
Response for Payment API::
class PaymentResponse {
Action:
AdditionalData:
Amount:
Authentication:
Details:
DonationToken:
FraudResult:
MerchantReference: 39b82c21-fe7d-4d6e-a6ac-108cdb498d75
Order:
OutputDetails:
PaymentData:
PspReference: 883617192418467H
Redirect:
RefusalReason: FRAUD-CANCELLED
RefusalReasonCode: 22
ResultCode: Cancelled
}

I cannot see anything on the web page to indicate that these are cancelled cards (although one would obviously want to test this use case). So are these intended to be cancelled? I am assuming that since this is the demo program written by Adyen (I have not altered the code at all) that the problem is not a bug in the code although obviously it could be.

Could you please let me know if there is a problem with these cards, if I am doing something wrong or if there are any known bugs with the demo code.

Many thanks,

Martin Vaughan


 |

 |

 |

This email is a service from Adyen.[R5VL00-MDXG]

    On Friday, 2 April 2021, 15:34:45 BST, Deepu K Sasidharan ***@***.***> wrote:  
 
 


Hi I tried this and couldn't reproduce. The test cards are working fine. Seems like in your case the request is going to fraud detection flow for some reason. Could be an intermittent test system issue. can you please try gain? if it still fails give me the psp ref from response i'll dig in further

**Comment by MPV65** [comment] 2021-04-06 10:50
Have just tried again with details:

Card number: 5555 4444 3333 1111
Expiry date: 03/30
Security code: 737

The payment response (including Psp ref) was:

class PaymentResponse {
  Action:
  AdditionalData:
  Amount:
  Authentication:
  Details:
  DonationToken:
  FraudResult:
  MerchantReference: 4eda8298-30d9-4fc1-8016-49cb5d3f7270
  Order:
  OutputDetails:
  PaymentData:
  PspReference: 883617705926653G
  Redirect:
  RefusalReason: FRAUD-CANCELLED
  RefusalReasonCode: 22
  ResultCode: Cancelled
}

**Comment by deepu105** [comment] 2021-04-06 11:00
Ya seems like fraud setting issue and since this is running on localhost it could be detected as fraud. I'm closing this as its a setting related issue and Adyen support should be able to help you if you encounter this again

**Closed by deepu105** 2021-04-06 11:00 UTC

**Comment by MPV65** [comment] 2021-04-07 11:07
I think the fact that this is running on localhost may indeed be the problem. However, would it be possible to describe the settings you have on your merchant account for 3DS authorization so I could try these? Thanks.

**Comment by deepu105** [comment] 2021-04-17 08:22
well mine is a testing account with PCI compliance enabled so don't know if that matters, but in any case this normally works fine on new accounts as well. I think support would be your best bet in figuring out whats going wrong with your account
